- max_seq_length: 512
- doc_stride: 128
- max_query_length: 64
- do_train: True
- do_eval: False
- set_type: train
- evaluate_during_training: False
- evaluate_every_training_epoch: False
- do_lower_case: True
- per_gpu_train_batch_size: 16
- per_gpu_eval_batch_size: 16
- learning_rate: 1.5e-5
- gradient_accumulation_steps: 1
- weight_decay: 0.0
- adam_epsilon: 1e-8
- max_grad_norm: 1.0
- num_train_epochs: 20
- max_steps: -1
- warmup_steps: 0
- n_best_size: 5
- max_answer_length: 30
- verbose_logging:
- logging_steps: 500
- eval_all_checkpoints: False
- no_cuda: False
- overwrite_output_dir: True
- overwrite_cache: True
- seed: 42
- local_rank: -1
- threads: 1
- n_gpu: 3
